ip_stream_name = "prod_ride_events"
op_stream_name = "prod_ride_predictions"
bucket_name = "prod-mlflow-models-code-owners"
ecr_repo_name = "prod_stream_model_duration"
lambda_function_local_path="../lambda_function.py"
docker_image_local_path="../Dockerfile"